In [1]:
import numpy as np
import pandas as pd

### 1. Data Type and Attributes

In [2]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
a2 = np.array([[1, 2.0, 3.3],
               [4.5, 5.5, 6]])
a2

array([[1. , 2. , 3.3],
       [4.5, 5.5, 6. ]])

In [4]:
a3 = np.array([[[1, 2, 3],
                [4, 5,6],
                [7, 8, 9]],
              [[10, 11, 12],
               [13, 14, 15],
               [16, 17, 18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [5]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [6]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [11]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [12]:
df = pd.DataFrame(a2)

In [13]:
df

0    1    2
0  1.0  2.0  3.3
1  4.5  5.5  6.0

### 2. Creating Arrays

In [17]:
#array of ones
array_ones = np.ones((2,3), dtype = int)
array_ones

array([[1, 1, 1],
       [1, 1, 1]])

In [22]:
#array of zeroes
array_zeroes = np.zeros((2,3), dtype = int)
array_zeroes

array([[0, 0, 0],
       [0, 0, 0]])

In [24]:
#random array of int values
array_int = np.random.randint(0, 20, size = (6,4))
array_int

array([[ 5, 18, 12, 18],
       [ 5,  6,  4,  9],
       [11, 19,  4, 19],
       [17,  8, 17, 11],
       [17,  4, 14, 12],
       [17,  9, 10, 11]])

In [27]:
#array of random numbers
array_rand = np.random.random((3,4))
array_rand

array([[0.77011107, 0.73615108, 0.52343689, 0.19560629],
       [0.06752185, 0.93248567, 0.72459067, 0.5011368 ],
       [0.63603353, 0.77385321, 0.66877458, 0.50657394]])

In [31]:
array_rand_1 = np.random.rand(5,5)
array_rand_1

array([[0.01085098, 0.51293283, 0.55002031, 0.65140652, 0.87802916],
       [0.60004499, 0.3811056 , 0.43968996, 0.08295866, 0.07747895],
       [0.92103512, 0.75914564, 0.54068547, 0.5849165 , 0.73022274],
       [0.24867267, 0.71718066, 0.84561901, 0.24431204, 0.12437648],
       [0.86782401, 0.06819452, 0.63967917, 0.07098016, 0.25541772]])

In [38]:
#array of numbers between certain range
array_1 = np.arange(0,20,2).reshape(2,5)
array_1

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [40]:
array_1.size, array_1.shape

(10, (2, 5))

In [46]:
#Pseudo random numbers
np.random.seed(0) #helps to keep number constant if the notebook has to be shared.
np.random.randint(0,30, size=(5,6))

array([[12, 15, 21,  0,  3, 27],
       [ 3,  7,  9, 19, 21, 18],
       [ 4, 23,  6, 24, 24, 12],
       [26,  1,  6,  7, 23, 14],
       [24, 17,  5, 25, 13,  8]])

#### Viewing Arrays and Matrices

In [47]:
#unique elements in the array
np.unique(array_int)

array([ 4,  5,  6,  8,  9, 10, 11, 12, 14, 17, 18, 19])

In [48]:
a1

array([1, 2, 3])

In [49]:
a2

array([[1. , 2. , 3.3],
       [4.5, 5.5, 6. ]])

In [50]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [51]:
a1[0]

1

In [52]:
a2[1]

array([4.5, 5.5, 6. ])

In [53]:
a3.shape

(2, 3, 3)

In [54]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [55]:
a3[:,:,:2]

array([[[ 1,  2],
        [ 4,  5],
        [ 7,  8]],

       [[10, 11],
        [13, 14],
        [16, 17]]])

In [57]:
a3[:1,:1,:2]

array([[[1, 2]]])

### Manipulating & Comparing arrays

In [58]:
a1

array([1, 2, 3])

In [59]:
a2

array([[1. , 2. , 3.3],
       [4.5, 5.5, 6. ]])

In [60]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [63]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [64]:
a1 + ones

array([2., 3., 4.])

In [65]:
a2 + ones

array([[2. , 3. , 4.3],
       [5.5, 6.5, 7. ]])

In [66]:
a3 + ones

array([[[ 2.,  3.,  4.],
        [ 5.,  6.,  7.],
        [ 8.,  9., 10.]],

       [[11., 12., 13.],
        [14., 15., 16.],
        [17., 18., 19.]]])

In [67]:
a1 * ones

array([1., 2., 3.])

In [68]:
a2 * ones

array([[1. , 2. , 3.3],
       [4.5, 5.5, 6. ]])

In [69]:
a3 * ones

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]],

       [[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]]])

In [70]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4.5, 11. , 18. ]])

In [71]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [79]:
a4 = a2.reshape(2,3,1)

In [80]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [77]:
a4

array([[[1. ],
        [2. ],
        [3.3]],

       [[4.5],
        [5.5],
        [6. ]]])

In [78]:
a4 * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 45. ,  49.5,  54. ],
        [ 71.5,  77. ,  82.5],
        [ 96. , 102. , 108. ]]])

In [83]:
a1

array([1, 2, 3])

In [82]:
a2

array([[1. , 2. , 3.3],
       [4.5, 5.5, 6. ]])

In [81]:
a2/a1

array([[1.  , 1.  , 1.1 ],
       [4.5 , 2.75, 2.  ]])

In [84]:
a2//a1 #floor division

array([[1., 1., 1.],
       [4., 2., 2.]])

In [85]:
a1 ** 2

array([1, 4, 9], dtype=int32)

In [86]:
np.square(a1)

array([1, 4, 9], dtype=int32)

In [87]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [20.25, 30.25, 36.  ]])

In [88]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [20.25, 30.25, 36.  ]])

In [89]:
np.add(a1,a2)

array([[2. , 4. , 6.3],
       [5.5, 7.5, 9. ]])

In [90]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

In [91]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

### Aggregations

In [92]:
a2

array([[1. , 2. , 3.3],
       [4.5, 5.5, 6. ]])

In [94]:
my_list = list([1,2,3])

In [95]:
my_list

[1, 2, 3]

In [96]:
sum(my_list)

6

In [97]:
a1

array([1, 2, 3])

In [98]:
sum(a1)

6

In [99]:
np.sum(a1)

6

In [100]:
massive_array = np.random.random(100000)

In [101]:
massive_array[ : 30]

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443,
       0.63992102, 0.14335329, 0.94466892, 0.52184832, 0.41466194,
       0.26455561, 0.77423369, 0.45615033, 0.56843395, 0.0187898 ,
       0.6176355 , 0.61209572, 0.616934  , 0.94374808, 0.6818203 ,
       0.3595079 , 0.43703195, 0.6976312 , 0.06022547, 0.66676672])

### When using python datatypes always (`sum()`) and when using numpy arrays always use (`np.sum()`)

In [102]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

16.7 ms ± 542 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
43.6 µs ± 1.3 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [105]:
np.mean(a1)

2.0

In [106]:
np.std(a1)

0.816496580927726

In [107]:
np.var(a1)

0.6666666666666666

In [109]:
np.sqrt(np.var(a1)) # Standard deviation is square root of variance

0.816496580927726

In [110]:
a2

array([[1. , 2. , 3.3],
       [4.5, 5.5, 6. ]])

### Transpose of a matrix

In [111]:
a2.T

array([[1. , 4.5],
       [2. , 5.5],
       [3.3, 6. ]])

In [112]:
a2.shape

(2, 3)

In [113]:
a2.T.shape

(3, 2)

In [114]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [115]:
a3.shape

(2, 3, 3)

In [116]:
a3.T

array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

In [118]:
a3.T.shape

(3, 3, 2)

### Element wise ( Hadamard Product) Vs Dot Product

In [127]:
np.random.seed(0)
mat1 = np.random.randint(10, size = (5,3))
mat2 = np.random.randint(10, size = (5,3))
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [128]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [122]:
#Multiply two matrices -- element wise multiplication (Hadamard Product)
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [125]:
#Dot Product : For this inner dimension of first matrix must be same outer dimension of second matrix such (5,3) and (3,5) 
#resulting in (5,5)
mat3 = np.dot(mat1, mat2.T)
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

In [126]:
mat3.shape

(5, 5)

### Dot Product Problem (Butter Store Sales)

In [137]:
np.random.seed(0)
weekly_sales = np.random.randint(20, size = (5,3))
weekly_sales

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [138]:
butter_prices = np.array([10,8,12])
butter_prices

array([10,  8, 12])

In [144]:
butter_prices.T.shape

(3,)

In [140]:
weekly_sales_df = pd.DataFrame(weekly_sales, 
                              index = ["Mon","Tue","Wed","Thu","Fri"],
                               columns = ["Almond Butter", "Peanut Butter", "Cashew Butter"])
weekly_sales_df

Almond Butter  Peanut Butter  Cashew Butter
Mon             12             15              0
Tue              3              3              7
Wed              9             19             18
Thu              4              6             12
Fri              1              6              7

In [145]:
butter_prices_df = pd.DataFrame(butter_prices.reshape(1,3), 
                              index = ["Price"],
                               columns = ["Almond Butter", "Peanut Butter", "Cashew Butter"])
butter_prices_df

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [146]:
np.dot(weekly_sales,butter_prices.T)

array([240, 138, 458, 232, 142])

In [149]:
weekly_sales_df.shape,butter_prices_df.T.shape

((5, 3), (3, 1))

In [150]:
daily_sales = weekly_sales_df.dot(butter_prices_df.T)

In [151]:
daily_sales

Price
Mon    240
Tue    138
Wed    458
Thu    232
Fri    142

In [152]:
weekly_sales_df["Total ($)"] = weekly_sales_df.dot(butter_prices_df.T)

In [154]:
weekly_sales_df

Almond Butter  Peanut Butter  Cashew Butter  Total ($)
Mon             12             15              0        240
Tue              3              3              7        138
Wed              9             19             18        458
Thu              4              6             12        232
Fri              1              6              7        142

In [165]:
from IPython.display import Image
Image(filename='C:\Vikas\Personal\Important\panda.jpg',width=800, height=400)

In [171]:
from matplotlib.image import imread
panda = imread('panda.jpg')
print(type(panda))

<class 'numpy.ndarray'>


In [172]:
panda

array([[[82, 86, 59],
        [85, 92, 61],
        [91, 98, 67],
        ...,
        [31, 57, 22],
        [31, 57, 22],
        [31, 57, 22]],

       [[81, 85, 58],
        [85, 90, 60],
        [91, 98, 67],
        ...,
        [32, 58, 23],
        [32, 58, 23],
        [32, 58, 23]],

       [[80, 84, 57],
        [84, 88, 61],
        [90, 97, 66],
        ...,
        [32, 57, 25],
        [32, 57, 25],
        [32, 57, 25]],

       ...,

       [[60, 62, 59],
        [69, 71, 68],
        [73, 75, 72],
        ...,
        [12, 12, 10],
        [12, 12, 10],
        [12, 12, 10]],

       [[65, 67, 64],
        [69, 71, 68],
        [71, 73, 70],
        ...,
        [11, 11,  9],
        [11, 11,  9],
        [11, 11,  9]],

       [[66, 68, 65],
        [65, 67, 64],
        [62, 64, 61],
        ...,
        [11, 11,  9],
        [11, 11,  9],
        [11, 11,  9]]], dtype=uint8)

In [173]:
panda.size, panda.shape, panda.ndim

(150975, (183, 275, 3), 3)