# Introduction to Scikit Learn (sklearn) Workflow

1. Get the data ready
2. Choose the model/estimator
3. Fit the model to the data and use it to make a prediction
4. Evaluate the model
5. Experiment to improve (hyperparameter tuning)
6. Save a model for later use

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")
import matplotlib.pyplot as plt
%matplotlib inline

# 1. Get the Data Ready

In [2]:
heart_disease = pd.read_csv('heart-disease.csv')
heart_disease.head(10)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   
5   57    1   0       140   192    0        1      148      0      0.4      1   
6   56    0   1       140   294    0        0      153      0      1.3      1   
7   44    1   1       120   263    0        1      173      0      0.0      2   
8   52    1   2       172   199    1        1      162      0      0.5      2   
9   57    1   2       150   168    0        1      174      0      1.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1  
5   0     1       1  
6   0     2       1  
7   0     3       1  
8   0     3       1  
9   0     2       1

In [3]:
heart_disease.shape

(303, 14)

In [4]:
# Create X (all features columns)
X = heart_disease.drop("target", axis = 1)

#Create y (the label column)
y = heart_disease["target"]

In [5]:
#Split the data into train and test splits
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [6]:
X_train.shape

(242, 13)

In [7]:
X_test.shape

(61, 13)

In [8]:
y_train.shape, y_test.shape

((242,), (61,))

# 2. Choose the model/estimator

In Scikit-Learn, machine learning models are referred to as estimators.

In this case, since we're working on a classification problem, we've chosen the RandomForestClassifier estimator which is part of the ensembles module.

In [9]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier() #instantiating the model object

clf.get_params() #parameters for the estimator/model

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

# 3. Fit the model to the data and use it to make a prediction

In [10]:
clf.fit(X_train, y_train);

In [11]:
# Make Predictions
y_preds = clf.predict(X_test)

In [12]:
# This will be in same format as y_test
y_preds

array([1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1], dtype=int64)

In [15]:
X_test.loc[275]

age          52.0
sex           1.0
cp            0.0
trestbps    125.0
chol        212.0
fbs           0.0
restecg       1.0
thalach     168.0
exang         0.0
oldpeak       1.0
slope         2.0
ca            2.0
thal          3.0
Name: 275, dtype: float64

In [16]:
heart_disease.loc[275]

age          52.0
sex           1.0
cp            0.0
trestbps    125.0
chol        212.0
fbs           0.0
restecg       1.0
thalach     168.0
exang         0.0
oldpeak       1.0
slope         2.0
ca            2.0
thal          3.0
target        0.0
Name: 275, dtype: float64

In [17]:
np.array(X_test.loc[275]).reshape(1, -1)

array([[ 52.,   1.,   0., 125., 212.,   0.,   1., 168.,   0.,   1.,   2.,
          2.,   3.]])

In [18]:
# Make a prediction on a single sample (has to be array)
clf.predict(np.array(X_test.loc[275]).reshape(1, -1))

array([0], dtype=int64)

# 4. Evaluate the model

In [19]:
# On the training set
clf.score(X_train, y_train)

1.0

In [20]:
# On the test set
clf.score(X_test, y_test)

0.819672131147541

In [21]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.75      0.78      0.77        23
           1       0.86      0.84      0.85        38

    accuracy                           0.82        61
   macro avg       0.81      0.81      0.81        61
weighted avg       0.82      0.82      0.82        61



In [22]:
print(confusion_matrix(y_test, y_preds))

[[18  5]
 [ 6 32]]


In [23]:
print(accuracy_score(y_test, y_preds))

0.819672131147541


# 5. Experiment to improve (hyperparameter tuning)

In [24]:
# Trying different number of estimators (n_estimators is the parameter to tune)
np.random.seed(42)

for i in range (10,110,10):
    print(f"Trying model with {i} estimators...")
    clf = RandomForestClassifier(n_estimators = i).fit(X_train, y_train)
    print(f"Model accuracy on test set : {clf.score(X_test, y_test) * 100}%")
    print("")

Trying model with 10 estimators...
Model accuracy on test set : 75.40983606557377%

Trying model with 20 estimators...
Model accuracy on test set : 73.77049180327869%

Trying model with 30 estimators...
Model accuracy on test set : 80.32786885245902%

Trying model with 40 estimators...
Model accuracy on test set : 80.32786885245902%

Trying model with 50 estimators...
Model accuracy on test set : 85.24590163934425%

Trying model with 60 estimators...
Model accuracy on test set : 85.24590163934425%

Trying model with 70 estimators...
Model accuracy on test set : 80.32786885245902%

Trying model with 80 estimators...
Model accuracy on test set : 83.60655737704919%

Trying model with 90 estimators...
Model accuracy on test set : 83.60655737704919%

Trying model with 100 estimators...
Model accuracy on test set : 83.60655737704919%



# 6. Save a model for later use

In [25]:
import pickle

In [26]:
#Save trained model to file

pickle.dump(clf, open("random_forest_model_1.pkl", "wb"))

In [27]:
# Load a saved model and make a prediction on a single example
loaded_model = pickle.load(open("random_forest_model_1.pkl", "rb"))
loaded_model.predict(np.array(X_test.loc[275]).reshape(1, -1))

array([0], dtype=int64)